import React from 'react';
import { motion } from 'framer-motion';
import { Info, ShieldCheck, ShieldAlert, ShieldQuestion } from 'lucide-react';

interface AuthenticityStatusBarProps {
    data?: {
        aiProbability: number;
        humanProbability: number;
        analysisReasoning: string;
    };
    hasResumeText?: boolean;
}

const AuthenticityStatusBar: React.FC<AuthenticityStatusBarProps> = ({ data, hasResumeText }) => {
    const hasData = !!(data?.analysisReasoning && data.analysisReasoning.length > 0);
    const aiProbability = data?.aiProbability ?? 0;
    const humanProbability = data?.humanProbability ?? 0;

    // Lenient Mode: treat as human if AI probability < 40%
    const isLikelyHuman = hasData && aiProbability < 40;
    const isHighAI = hasData && aiProbability > 72;
    const humanPercentage = isLikelyHuman ? 100 : humanProbability;

    const statusIcon = !hasData ? <ShieldQuestion size={16} className="text-slate-500" /> :
        isLikelyHuman ? <ShieldCheck size={16} className="text-emerald-400" /> :
            <ShieldAlert size={16} className={isHighAI ? 'text-rose-500' : 'text-amber-500'} />;

    const statusLabel = !hasData ? 'Not Analyzed'
        : isLikelyHuman ? '✓ 100% Human'
            : `${humanProbability}% Human`;

    const statusColor = !hasData ? 'text-slate-500'
        : isLikelyHuman ? 'text-emerald-400 font-black'
            : isHighAI ? 'text-rose-500 font-black' : 'text-amber-500 font-black';

    return (
        <div className="mt-6 mb-2 p-5 bg-slate-800/60 rounded-3xl border border-white/10 shadow-2xl backdrop-blur-md">
            {/* Header row */}
            <div className="flex items-center justify-between mb-2">
                <div className="flex items-center gap-3">
                    <div className={`p-2 rounded-xl ${!hasData ? 'bg-slate-700/30' : isLikelyHuman ? 'bg-emerald-500/20' : 'bg-rose-500/20'}`}>
                        {statusIcon}
                    </div>
                    <div>
                        <div className="flex items-center gap-2">
                            <span className="text-[11px] font-black text-white uppercase tracking-[0.2em]">Fairness Score</span>
                            <div className="group relative">
                                <Info size={12} className="text-slate-500 cursor-help hover:text-white transition-colors" />
                                <div className="absolute bottom-full left-0 mb-3 w-64 p-4 bg-slate-900 border border-white/20 rounded-2xl text-[10px] text-slate-300 opacity-0 group-hover:opacity-100 transition-all pointer-events-none z-50 shadow-[0_20px_50px_rgba(0,0,0,0.5)] leading-relaxed">
                                    <strong className="text-primary-400 block mb-1">How it works:</strong>
                                    We analyze writing tempo, structural repetition, and vocabulary diversity. Lenient Mode is active: anything below 40% AI probability is verified as human.
                                </div>
                            </div>
                        </div>
                        <p className="text-[9px] text-slate-400 font-medium uppercase tracking-tight opacity-70">Detection Intelligence</p>
                    </div>
                </div>
                <div className="text-right">
                    <span className={`text-[13px] block ${statusColor} drop-shadow-[0_0_10px_rgba(0,0,0,0.5)]`}>
                        {statusLabel}
                    </span>
                </div>
            </div>

            {/* Description */}
            <p className="text-[11px] text-slate-300/80 mb-5 leading-relaxed font-medium mt-2">
                "AI-powered analysis of writing style, vocabulary, and structure to detect whether this resume was written by a human or generated by an AI tool."
            </p>

            {/* Bar Container */}
            <div className="relative pt-1">
                <div className="h-2.5 w-full bg-slate-950/80 rounded-full overflow-hidden border border-white/5 p-[1px]">
                    {hasData ? (
                        <motion.div
                            initial={{ width: 0 }}
                            animate={{ width: `${humanPercentage}%` }}
                            transition={{ duration: 1.8, ease: [0.34, 1.56, 0.64, 1] }}
                            className={`h-full rounded-full relative ${isLikelyHuman
                                ? 'bg-gradient-to-r from-emerald-600 via-emerald-500 to-emerald-400'
                                : humanPercentage > 60
                                    ? 'bg-gradient-to-r from-emerald-500 via-amber-400 to-amber-500'
                                    : 'bg-gradient-to-r from-amber-500 via-rose-500 to-rose-600'
                                }`}
                        >
                            {/* Glow effect for the bar tip */}
                            <div className="absolute right-0 top-0 bottom-0 w-8 bg-white/20 blur-sm rounded-full" />
                        </motion.div>
                    ) : (
                        <div className="h-full w-full bg-slate-800/40 rounded-full flex items-center justify-center">
                            <motion.div
                                animate={{ x: ['-100%', '100%'] }}
                                transition={{ repeat: Infinity, duration: 2, ease: "linear" }}
                                className="w-1/3 h-full bg-gradient-to-r from-transparent via-white/10 to-transparent"
                            />
                        </div>
                    )}
                </div>

                {/* Scale labels */}
                <div className="flex justify-between mt-2.5 px-1">
                    <div className="flex flex-col items-start gap-1">
                        <span className="text-[10px] text-emerald-500 font-black uppercase tracking-tighter">Human Authored</span>
                        <div className="w-12 h-1 bg-emerald-500/20 rounded-full" />
                    </div>
                    <div className="flex flex-col items-end gap-1">
                        <span className="text-[10px] text-rose-500 font-black uppercase tracking-tighter">AI Generated</span>
                        <div className="w-12 h-1 bg-rose-500/20 rounded-full" />
                    </div>
                </div>
            </div>

            {/* Reasoning or pending */}
            <div className="mt-6 pt-4 border-t border-white/10">
                {hasData ? (
                    <div className="flex gap-2">
                        <div className="mt-1 w-1 h-1 rounded-full bg-primary-400 shrink-0" />
                        <p className="text-[11px] text-slate-300 leading-relaxed italic">
                            <span className="text-primary-400 font-bold not-italic px-1">AI INSIGHT:</span>
                            {data!.analysisReasoning}
                        </p>
                    </div>
                ) : hasResumeText ? (
                    // Has resume text — AI is processing it in the background
                    <div className="flex items-center gap-3 px-3 py-2 bg-amber-500/5 rounded-xl border border-amber-500/15">
                        <div className="flex gap-0.5">
                            <div className="w-1.5 h-1.5 rounded-full bg-amber-500 animate-bounce [animation-delay:0ms]" />
                            <div className="w-1.5 h-1.5 rounded-full bg-amber-500 animate-bounce [animation-delay:150ms]" />
                            <div className="w-1.5 h-1.5 rounded-full bg-amber-500 animate-bounce [animation-delay:300ms]" />
                        </div>
                        <p className="text-[10px] text-amber-500/80 font-semibold tracking-tight">
                            AI scanning resume... result will appear shortly
                        </p>
                    </div>
                ) : (
                    // No resume at all
                    <div className="flex items-center gap-2 px-3 py-2 bg-slate-900/40 rounded-xl border border-white/5">
                        <div className="w-1.5 h-1.5 rounded-full bg-slate-600" />
                        <p className="text-[10px] text-slate-500 font-medium tracking-tight">
                            Student has not uploaded a resume yet
                        </p>
                    </div>
                )}
            </div>
        </div>
    );
};

export default AuthenticityStatusBar;
